version: "3.8"
networks:
  walnut01:
    driver: bridge
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    networks:
      - walnut01
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - URL=walnuthomelab.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare	
    volumes:
      - ${DOCKERCONFDIR}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
